[package]
name = "rust-synthetic-price-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
plotly = "0.12.1"
polars = "0.46.0"
rand = "0.9.0"
rand_distr = "0.5.0"
rayon = "1.10.0"
